### ISSUE TITLE
Graphics.IsInPit and .IsInPitlane not Working from ACC

### ISSUE THREAD

**Issue by Dandrum** [Thomseeen/AccTools#1]
The Graphics.IsInPitLane and Graphics.IsInPit dont change value from 0 to 1 if i enter or leave Pit In ACC.

**Comment by Thomseeen** [comment]
Hi Dandrum, I don't know when `Graphics.IsInPitLane` is supposed to change. If it is supposed to reflect the cars position being anywhere in the pits, then yes, it isn't working, but that's an issue of the SharedMemory Map from ACC, not this lib, as far as I can tell. I can however confirm that `Graphics.IsInPit` does change when you are in the pit screen.

**Comment by Thomseeen** [comment]
Never mind... I found some changes in the shared memory structs. Fixing them right now. I will test and upload the new models and a nuget later.

**Comment by Thomseeen** [comment]
Fixed in 8b0c385246bf713f109b8eb229d580b8efa9c1f0

**Comment by Dandrum** [comment]
Your the best <3 

The Graphics.IsInPitLange changes when the car leaves or enter PitLan (Works in SimHub). The Graphics.IsInPit should be changing whenn in pit screen..

I will try, thank you for your help.
