### ISSUE TITLE
Acc Shared Memory update ?

### ISSUE THREAD

**Issue by Dandrum** [Thomseeen/AccTools#2]
Hi Thomsen,

I use your implementation and nuget package for a ACC data Logger but currently it always shows "AccVersion":"1.7". Is there maybe a never Shared Memory Version you need to update in your package ? Cause acc is on Version 1.9. 

Thanks for your help.

**Comment by Thomseeen** [comment]
What exactly shows "AccVersion": "1.7"? You mean the [`ACVersion` field in the `StaticInfo` struct](https://github.com/Thomseeen/Thomsen.AccTools/blob/75a7c9dd2ed699f13b5de04b21aeceb264d3ee79/src/Thomsen.AccTools.SharedMemory/Models/StaticInfo.cs#LL12C29-L12C29)? It is, like all other fields in all other structs, filled by ACC. There is no hard coded version string on my end anywhere.

**Comment by Dandrum** [comment]
Ah ok, well then its wrong by ACC.. thanks
